Experimental CMake-based build system
This patch adds an experimental CMake-based build-system for Seastar.

It should be at feature-parity with the existing `configure.py` and
`test.py` scripts, including DPDK, documentation targets, and tests.
However, some features of those scripts are deprecated and have not been
translated over.

The primary way to build an application against Seastar with this build
system is to clone the Seastar repository and then, in your own
application's CMakeLists.txt file, to link against the imported target.
Nothing else should be necessary.

add_subdirectory (${MY_SEASTAR_CLONE_DIR})
add_executable (my_app my_app_source.cc)
target_link_libraries (my_app Seastar::seastar)

In case your application does not build with CMake, a pkg-config
file (`seastar.pc`) is built with the `pkg-config` target in the build
directory.

Quick start:
$ mkdir build-cmake
$ cd build-cmake
$ cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
$ ninja-build
$ ctest -j4 # Run tests.
$ ctest -j4 -R allocator # Run tests matching the pattern.

Future work:

- Replacement `configure.py` and `test.py` scripts that call into the
  CMake equivalents.

Known issues:

- DPDK compilation fails:

CC scheduler_pmd.o
/home/jhaberku/src/seastar/dpdk/drivers/crypto/scheduler/scheduler_pmd.c:39:10: fatal error: rte_reorder.h: No such file or directory

- CMake doens't like '#' characters, so running the compiler with
  -Wno-error=#warning confuses. I'm tried escaping the character with no
  success.